/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-12-27 06:38:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import product.*;
import search.*;
import java.util.*;

public final class singleBiddingProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/include/footer.jsp", Long.valueOf(1514356622538L));
    _jspx_dependants.put("/include/css_js.jsp", Long.valueOf(1514356622531L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("product");
    _jspx_imports_packages.add("search");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html lang=\"zh-TW\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>AS拍</title>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 掛載CSS樣式 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 掛載JS樣式 -->\r\n");
      out.write("<script src=\"./js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"./js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"./js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"./js/main.js\"></script>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction addPrice(){\r\n");
      out.write("\t\t\tdocument.singleBiddingProductForm.action = \"addPriceServlet\";\r\n");
      out.write("\t\t\tdocument.singleBiddingProductForm.submit();\r\n");
      out.write("\t\t\talert(\"加價成功\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction directlyBuy(){\r\n");
      out.write("\t\t\tdocument.singleBiddingProductForm.action = \"directlyBuyServlet\";\r\n");
      out.write("\t\t\tdocument.singleBiddingProductForm.submit();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");


	String userAccount = (String)session.getAttribute("userId");
	int bidId = Integer.parseInt(request.getParameter("bidId"));
	
	biddingItem item = search.searchSingleBid(bidId);


      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 上方選單 -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/topLink.jsp", out, true);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 結標後要秀出已結標，立即加價Button關閉點擊 -->\r\n");
      out.write("\t<!-- 內容區 -->\r\n");
      out.write("\t<div id=\"singleBiddingProduct_content\" class=\"content\">\r\n");
      out.write("\t    <div class=\"content_container\">\r\n");
      out.write("\t        <div id=\"singleBiddingProduct_content_top\" class=\"left\">\r\n");
      out.write("\t            <form id=\"singleBiddingProductForm\" name=\"singleBiddingProductForm\" class=\"center\" action=\"\">\r\n");
      out.write("\t            \t<input type=\"hidden\" name=\"bidId\" value=\"");
      out.print(item.getBidId());
      out.write("\">\r\n");
      out.write("\t                <input type=\"hidden\" name=\"priceNow\" value=\"");
      out.print(item.getPriceNow());
      out.write("\">\r\n");
      out.write("\t                <input type=\"hidden\" name=\"priceIncrease\" value=\"");
      out.print(item.getPriceIncrease());
      out.write("\">\r\n");
      out.write("\t\r\n");
      out.write("\t                <div class=\"single_img left\"><img src=\"./images/content-01.jpg\"></div>\r\n");
      out.write("\t                <div class=\"single_field left\">\r\n");
      out.write("\t                \t<div class=\"form-group col-md-10\">\r\n");
      out.write("\t                        <p>販售人：<a href=\"memberProfile.jsp?userId=");
      out.print(item.getSellerId());
      out.write("\" title=\"");
      out.print(item.getSellerId() );
      out.write('"');
      out.write('>');
      out.print(item.getSellerId() );
      out.write("</a></p>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"form-group col-md-10\">\r\n");
      out.write("\t                        <p>商品：");
      out.print(item.getName() );
      out.write("</p>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"form-group col-md-10\">\r\n");
      out.write("\t                        <p>結標時間： ");
      out.print(item.getEndTime() );
      out.write("</p>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"form-group col-md-10\">\r\n");
      out.write("\t                        <p>起始金額： $");
      out.print(item.getPriceMin() );
      out.write("</p>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"form-group col-md-10\">\r\n");
      out.write("\t                        <p>目前最高金額： $");
      out.print(item.getPriceNow() );
      out.write("</p>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"form-group col-md-10\">\r\n");
      out.write("\t                        <p>每次加價金額： $");
      out.print(item.getPriceIncrease() );
      out.write("</p>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"form-group col-md-10\">\r\n");
      out.write("\t                        <p>直購金額： $");
      out.print(item.getPriceMax() );
      out.write("</p>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    ");
 if( userAccount != null && !userAccount.equals("null") && !userAccount.equals("") && !userAccount.equals(item.getSellerId()) ) {
      out.write("\r\n");
      out.write("\t                    <div class=\"form-group col-md-10\">\r\n");
      out.write("\t                        <button type=\"button\" class=\"btn btn-danger\" onclick=\"addPrice()\">立即加價</button>\r\n");
      out.write("\t                        <button type=\"button\" class=\"btn btn-warning\" onclick=\"directlyBuy()\">直接購買</button>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    ");
} 
      out.write("\r\n");
      out.write("\t                    <div class=\"form-group col-md-10\">\r\n");
      out.write("\t                        <p class=\"outOfNumber\">＊ 已結標</p>\r\n");
      out.write("\t                        <p class=\"outOfNumber\">＊ 結標價錢： $");
      out.print(item.getPriceNow() );
      out.write("</p>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\r\n");
      out.write("\t            </form>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div id=\"singleBiddingProduct_content_bottom\" class=\"left\">\r\n");
      out.write("\t            <nav class=\"nav nav-tabs\" id=\"myTab\" role=\"tablist\">\r\n");
      out.write("\t                <a class=\"nav-item nav-link active\" id=\"nav-home-tab\" data-toggle=\"tab\" href=\"#nav-home\" role=\"tab\" aria-controls=\"nav-home\" aria-selected=\"true\">商品詳細說明</a>\r\n");
      out.write("\t                <a class=\"nav-item nav-link\" id=\"nav-profile-tab\" data-toggle=\"tab\" href=\"#nav-profile\" role=\"tab\" aria-controls=\"nav-profile\" aria-selected=\"false\">問與答</a>\r\n");
      out.write("\t            </nav>\r\n");
      out.write("\t            <div class=\"tab-content\" id=\"nav-tabContent\" style=\"margin-top: 1rem;\">\r\n");
      out.write("\t                <div class=\"tab-pane fade show active\" id=\"nav-home\" role=\"tabpanel\" aria-labelledby=\"nav-home-tab\">\r\n");
      out.write("\t                    ");
      out.print(item.getDescription() );
      out.write("\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"tab-pane fade\" id=\"nav-profile\" role=\"tabpanel\" aria-labelledby=\"nav-profile-tab\">\r\n");
      out.write("\t                   <ul id=\"faq_list\">\r\n");
      out.write("\t\t                \t<li>\r\n");
      out.write("\t\t\t                    <div>\r\n");
      out.write("\t\t\t                    \t<p>問： ?????</p>\r\n");
      out.write("\t\t\t                    \t<p>答： ?????</p>\r\n");
      out.write("\t\t\t                    </div>\r\n");
      out.write("\t\t\t                    <div>問答人</div>\r\n");
      out.write("\t\t                    </li>\r\n");
      out.write("\t\t                    <li>\r\n");
      out.write("\t\t\t                    <div>\r\n");
      out.write("\t\t\t                    \t<p>問： ?????</p>\r\n");
      out.write("\t\t\t                    \t<p>答： ?????</p>\r\n");
      out.write("\t\t\t                    </div>\r\n");
      out.write("\t\t\t                    <div>問答人</div>\r\n");
      out.write("\t\t                    </li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                    <form id=\"faqForm\" name=\"faqForm\">\r\n");
      out.write("\t                    <div class=\"form-group col-md-8 center\">\r\n");
      out.write("\t                    \t\t<label for=\"buyer_area\">我要提問</label>\r\n");
      out.write("\t                \t\t\t<textarea name=\"buyer_area\" class=\"form-control\" id=\"buyer_area\" rows=\"5\"></textarea>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"col-md-6 text_center center\" style=\"margin-top: 10px;\">\r\n");
      out.write("\t\t\t                <button type=\"submit\" class=\"btn btn-primary \">確認送出</button>\r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t            </form>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 網站資訊 -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"left footer\">\r\n");
      out.write("\t 網站基本資訊\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
