/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-12-27 06:37:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.http.HttpSession;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public final class topLink_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
    _jspx_imports_classes.add("javax.servlet.http.HttpServletRequest");
    _jspx_imports_classes.add("javax.servlet.http.HttpServletResponse");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


	String userAccount = (String)session.getAttribute("userId");
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"index.jsp\" title=\"AS拍\">AS拍</a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarColor01\" aria-controls=\"navbarColor01\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarColor01\">\r\n");
      out.write("            <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"shoppingMall.jsp\" title=\"購物商場\">購物商場</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"biddingMall.jsp\" title=\"競標商場\">競標商場 </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                ");
 if(userAccount != null && !userAccount.equals("null") && !userAccount.equals("")) {
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink_buyer\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\" title=\"我是買家\">\r\n");
      out.write("                       \t 我是買家\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink_buyer\">\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"auctionProductOverview_buyer.jsp\" title=\"拍賣商品概況\">拍賣商品概況</a>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"biddingProductOverview_buyer.jsp\" title=\"競標商品概況\">競標商品概況</a>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"evaluation.jsp\" title=\"評價系統\">評價系統</a>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"history.jsp\" title=\"歷史紀錄\">歷史紀錄</a>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"order_buyer.jsp\" title=\"訂單\">訂單</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink_seller\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\" title=\"我是賣家\">\r\n");
      out.write("                        \t我是賣家\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink_seller\">\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"publishAuctionProduct.jsp\" title=\"刊登拍賣商品\">刊登拍賣商品</a>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"publishBiddingProduct.jsp\" title=\"刊登競標商品\">刊登競標商品</a>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"auctionProductOverview_seller.jsp\" title=\"拍賣商品概況\">拍賣商品概況</a>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"biddingProductOverview_seller.jsp\" title=\"競標商品概況\">競標商品概況</a>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"order_seller.jsp\" title=\"訂單\">訂單</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"discount.jsp\" title=\"可用優惠\">可用優惠 </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <form id=\"searchForm\" class=\"form-inline\" action=\"search.jsp\">\r\n");
      out.write("                <input class=\"form-control mr-sm-2\" id=\"keyword\" name=\"keyword\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("                <div class=\"form-group mr-sm-2\">\r\n");
      out.write("                    <label for=\"mallCategory\"></label>\r\n");
      out.write("                    <select id=\"mallCategory\" class=\"form-control\" name=\"mallCategory\">\r\n");
      out.write("                        <option value=\"auction\" selected>拍賣商品</option>\r\n");
      out.write("                        <option value=\"bid\">競標商品</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group mr-sm-2\">\r\n");
      out.write("                    <label for=\"productCategory\"></label>\r\n");
      out.write("                    <select id=\"productCategory\" class=\"form-control\" name=\"productCategory\">\r\n");
      out.write("                    \t<option value=\"\" selected></option>\r\n");
      out.write("                        <option value=\"Digit\">3C數位</option>\r\n");
      out.write("                        <option value=\"Appliances\">家電</option>\r\n");
      out.write("                        <option value=\"Food\">食品</option>\r\n");
      out.write("                        <option value=\"Apparel\">服飾</option>\r\n");
      out.write("                        <option value=\"MakeUps\">美妝</option>\r\n");
      out.write("                        <option value=\"Life\">生活</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button class=\"btn btn-outline-info my-2 my-sm-0\" type=\"submit\" title=\"搜尋\">搜尋</button>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"navbar-nav\">\r\n");
      out.write("            \t");
 if(userAccount != null && !userAccount.equals("null") && !userAccount.equals("")) {
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a id=\"shopCart\" class=\"nav-link\" href=\"shoppingCart.jsp\" title=\"購物車\"><img src=\"./images/shopCart-1.png\"></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"member.jsp\" title=\"會員中心\">會員中心</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"signOutServlet\" title=\"登出\">登出</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("                ");
 if(userAccount == null || userAccount.equals("null") || userAccount.equals("")) {
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"signin.jsp\" title=\"登入\">登入</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"register.jsp\" title=\"註冊\">註冊</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <!-- 這邊為商品分類，縮成漢堡選單時才會顯示 -->\r\n");
      out.write("            <ul id=\"itemCategory_one\" class=\"navbar-nav\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <span style=\"color: #28a745;\" title=\"商品分類\">商品分類： </span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link category_child1\" href=\"search.jsp?mallCategory=auction&productCategory=Digit\" title=\"3C數位 ( Digit )\">3C數位</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link category_child2\" href=\"search.jsp?mallCategory=auction&productCategory=Appliances\" title=\"家電 ( Appliances )\">家電</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link category_child3\" href=\"search.jsp?mallCategory=auction&productCategory=Food\" title=\"食品 ( Food )\">食品</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link category_child4\" href=\"search.jsp?mallCategory=auction&productCategory=Apparel\" title=\"服飾 ( Apparel )\">服飾</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link category_child5\" href=\"search.jsp?mallCategory=auction&productCategory=Makeups\" title=\"美妝 ( Makeups )\">美妝</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link category_child6\" href=\"search.jsp?mallCategory=auction&productCategory=Life\" title=\"生活 ( Life )\">生活</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- 選單商品分類，螢幕太小會不顯示(上面的漢堡選單分類才顯示) -->\r\n");
      out.write("    <div style=\"width:100%; background-color: #ddd;\">\r\n");
      out.write("        <ul id=\"itemCategory_two\" class=\"nav \">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <span style=\"padding: .5rem 1rem; display: block;\">商品分類：</span>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link category_child1\" href=\"search.jsp?mallCategory=auction&productCategory=Digit\" title=\"3C數位 ( Digit )\">3C數位</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link category_child2\" href=\"search.jsp?mallCategory=auction&productCategory=Appliances\" title=\"家電 ( Appliances )\">家電</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link category_child3\" href=\"search.jsp?mallCategory=auction&productCategory=Food\" title=\"食品 ( Food )\">食品</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link category_child4\" href=\"search.jsp?mallCategory=auction&productCategory=Apparel\" title=\"服飾 ( Apparel )\">服飾</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link category_child5\" href=\"search.jsp?mallCategory=auction&productCategory=Makeups\" title=\"美妝 ( Makeups )\">美妝</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link category_child6\" href=\"search.jsp?mallCategory=auction&productCategory=Life\" title=\"生活 ( Life )\">生活</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
